/* Real product descriptions and legal pages, harvested from the live shop,
   become two data files the prototype loads alongside the catalogue:

     public/shop/content.js  — CONTENT: id -> sanitized description HTML
     public/shop/legal.js    — LEGAL: slug -> {title, html} for the info pages

   Sanitization is deliberately blunt: the HTML is the merchant's own, but it
   rode in through a Shopify editor, so scripts, styles, iframes, event
   handlers and images are stripped (cdn.shopify.com images die the day the
   store closes — text must stand alone). */

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = "C:/Users/Dmitri.MARKIT/source/repos/rempire-web";
const HARVEST = path.join(ROOT, "tools", "harvest");
const EXPORTS = "C:/Users/DMITRI~1.MAR/AppData/Local/Temp/claude/C--Users-Dmitri-MARKIT-source-repos-Rempire/d86fba33-c4c4-4dad-a0f6-a1d47ab1c4e3/scratchpad/exports";

function sanitize(html) {
  if (!html) return "";
  let s = String(html);
  s = s.replace(/<(script|style|iframe|object|embed|form|svg)[\s\S]*?<\/\1>/gi, "");
  s = s.replace(/<(img|source|video|audio|picture)\b[^>]*>/gi, "");
  s = s.replace(/\son\w+="[^"]*"/gi, "").replace(/\son\w+='[^']*'/gi, "");
  s = s.replace(/\s(style|class|id|dir|data-[\w-]+)="[^"]*"/gi, "");
  s = s.replace(/\s(style|class|id|dir|data-[\w-]+)='[^']*'/gi, "");
  s = s.replace(/<a\b[^>]*href="(javascript:)[^"]*"[^>]*>/gi, "<a>");
  // meta spans Shopify's editor loves
  s = s.replace(/<span>\s*<\/span>/g, "");
  s = s.replace(/<p>(\s|&nbsp;)*<\/p>/gi, "");
  s = s.replace(/\r/g, "").replace(/\n{3,}/g, "\n\n").trim();
  return s;
}

// ---------- products ----------
const catSrc = await readFile(path.join(ROOT, "public/shop/catalogue.js"), "utf8");
const CATALOGUE = new Function(catSrc + "\nreturn CATALOGUE;")();
const ids = CATALOGUE.map(p => p.id);

const content = {};
const files = await readdir(path.join(HARVEST, "products"));
for (const f of files) {
  if (!f.endsWith(".json")) continue;
  const j = JSON.parse(await readFile(path.join(HARVEST, "products", f), "utf8"));
  const p = j.product;
  const id = f.replace(/\.json$/, "");
  const clean = sanitize(p.body_html);
  if (clean.length > 40) content[id] = clean;
}

// the two drafts live only in the admin CSV (column 3 = Body (HTML))
const csv = await readFile(path.join(EXPORTS, "products_export_1.csv"), "utf8");
function csvBody(handle) {
  const i = csv.indexOf("\n" + handle + ",");
  if (i < 0) return null;
  // Body is the 3rd field, quoted; parse just this row's start
  const row = csv.slice(i + 1, i + 60000);
  const m = row.match(/^[^,]*,(?:"[^"]*"|[^,]*),"((?:[^"]|"")*)"/s);
  return m ? m[1].replace(/""/g, '"') : null;
}
for (const id of ["tom-ford-tobacco-vanille-eau-de-parfum-50ml", "creed-original-vetiver-eau-de-parfum-50ml"]) {
  if (!content[id]) {
    const b = csvBody(id);
    if (b) { const clean = sanitize(b); if (clean.length > 40) content[id] = clean; }
  }
}

const missing = ids.filter(id => !content[id]);
const js = "/* Generated by tools/build-content.mjs from the live shop's own\n" +
  "   descriptions (harvest of " + new Date().toISOString().slice(0, 10) + "). Do not edit by hand. */\n" +
  "var CONTENT = " + JSON.stringify(content, null, 0) + ";\n";
await writeFile(path.join(ROOT, "public/shop/content.js"), js, "utf8");

/* The harvested policy pages still trade as THEFLOW OÜ / 16320586 and carry a
   Gmail address nobody reads (audit item 13). The company identity is not a
   constant any more — it is settings.content, edited in «Настройки → Контент» —
   so the texts carry placeholders that public/shop2/app.js fills in at render
   time (cResolve()). The legal WORDING is untouched; only the identity moves. */
const IDENTITY = [
  ["THEFLOW OÜ", "{{legalName}}"],
  ["16320586", "{{regCode}}"],
  ["Mardi 1-3, 10113, Tallinn", "{{address}}"],
  ["blackboxestonia@gmail.com", "{{email}}"],
  ["rempireshopinfo@gmail.com", "{{email}}"],
  ["+372 5623 72 37", "{{phone}}"],
];
function identity(html) {
  let s = String(html || "");
  for (const [from, to] of IDENTITY) s = s.split(from).join(to);
  return s;
}

// ---------- legal pages ----------
const PAGES = [
  ["shipping", "shipping-policy.html", "Доставка и оплата"],
  ["returns", "refund-policy.html", "Возврат товара"],
  ["terms", "terms-of-service.html", "Условия продажи"],
  ["privacy", "privacy-policy.html", "Конфиденциальность"],
  ["contact", "contact.html", "Контакты"],
];
const legal = {};
for (const [slug, file, title] of PAGES) {
  try {
    const html = await readFile(path.join(HARVEST, "pages", file), "utf8");
    const clean = identity(sanitize(html));
    if (clean.length > 100) legal[slug] = { title, html: clean };
  } catch (e) { /* absent page just doesn't render a link */ }
}
await writeFile(path.join(ROOT, "public/shop/legal.js"),
  "/* Generated by tools/build-content.mjs — the live shop's own policy texts,\n" +
  "   to be replaced by lawyer-reviewed versions before launch. */\n" +
  "var LEGAL = " + JSON.stringify(legal, null, 0) + ";\n", "utf8");

// ---------- redirect map ----------
const urls = (await readFile(path.join(HARVEST, "old-urls.txt"), "utf8")).split(/\r?\n/).filter(Boolean);
const rows = [["old_url", "new_path", "kind", "note"]];
const knownIds = new Set(ids);
for (const u of urls) {
  let url; try { url = new URL(u); } catch (e) { continue; }
  const p = url.pathname;
  const lang = p.match(/^\/(et|en)(\/|$)/) ? p.split("/")[1] : "";
  const core = lang ? p.slice(lang.length + 1) : p;
  let out = null, kind = "", note = lang ? "lang:" + lang : "";
  let m;
  if ((m = core.match(/^\/products\/([^/]+)\/?$/))) {
    kind = "product";
    out = knownIds.has(m[1]) ? "/shop/p/" + m[1] + "/" : "/shop/";
    if (!knownIds.has(m[1])) note += (note ? " " : "") + "product-not-in-v1";
  } else if ((m = core.match(/^\/collections\/([^/]+)\/?$/))) {
    kind = "collection"; out = "/shop/"; note += (note ? " " : "") + "map-manually:" + m[1];
  } else if (core.startsWith("/blogs/")) {
    kind = "blog"; out = "/shop/";
  } else if (core.startsWith("/pages/") || core.startsWith("/policies/")) {
    kind = "page"; out = "/shop/info/" + (core.split("/")[2] || "");
  } else if (core === "/" || core === "") {
    kind = "home"; out = "/shop/";
  } else { kind = "other"; out = "/shop/"; }
  rows.push([u, out, kind, note]);
}
await writeFile(path.join(ROOT, "docs/redirect-map.csv"),
  rows.map(r => r.map(c => '"' + String(c).replace(/"/g, '""') + '"').join(",")).join("\n"), "utf8");

console.log(JSON.stringify({
  content: Object.keys(content).length,
  expected: ids.length,
  missing,
  legal: Object.keys(legal),
  redirects: rows.length - 1
}, null, 1));
