/* Writes src/data/legal-slugs.json — the keys of LEGAL in
   public/shop/legal.js, and nothing else. Runs in `prebuild`, beside
   tools/pack-content.mjs; idempotent.

   Why a generated file. `isKnownShopPath()` in src/lib/notfound-page.ts has to
   know which five `/shop2/info/<slug>/` addresses exist, and until 08.09.2026
   it read them off the directories `npm run prerender` writes under
   public/shop2/info/ — "so the two can never drift". They cannot, but the
   directory is not there to read: `outputFileTracingIncludes` in next.config.ts
   traces only public/shop2/index.html into /shop2/**, so in a Vercel function
   the readdir always failed, the check fell through to "let every slug
   through", and /shop2/info/<anything>/ answered 200 with the shell — a soft
   404, unbounded in number, found against staging on 08.09.2026. The check
   worked locally and was off in every deployment, which is the worst place for
   a check to be.

   A module the TypeScript imports has neither problem: Next traces it into the
   bundle because the source names it, and nothing is read at request time.

   Drift is still impossible, and by the same construction as before: this
   takes `Object.keys(LEGAL)` from public/shop/legal.js, which is the exact
   expression tools/prerender-shop2.mjs uses to decide which directories to
   write (LEGAL_SLUGS, and the router in app.js gates on LEGAL[slug] too).
   tools/check-prerender.mjs re-derives the same list a third time and fails on
   a directory that is not in it. The JSON is committed, like every other
   src/data/*.json a packer writes, so `tsc`, `vitest` and a fresh clone all
   have it without a build. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, "..", "public", "shop", "legal.js");
const OUT = path.join(HERE, "..", "src", "data", "legal-slugs.json");

function die(msg) {
  console.error("pack-legal: " + msg);
  process.exit(1);
}

if (!fs.existsSync(SRC)) die("no public/shop/legal.js — it is generated by tools/build-content.mjs");

/* legal.js is `var LEGAL = {…}` and nothing else, the same shape
   prerender-shop2.mjs and check-prerender.mjs evaluate rather than parse. */
let LEGAL;
try {
  LEGAL = new Function(fs.readFileSync(SRC, "utf8") + "\nreturn LEGAL;")();
} catch (err) {
  die("could not evaluate public/shop/legal.js (" + err.message + ")");
}
if (!LEGAL || typeof LEGAL !== "object" || Array.isArray(LEGAL)) {
  die("LEGAL in public/shop/legal.js is not an object of slug → page");
}

const slugs = Object.keys(LEGAL);
/* A slug is a path segment the router matches with /^[a-z]+$/ (app.js
   routeFromPath). One that could not be matched would be a page nobody can
   reach, so it is a build failure rather than a line in a JSON file. */
for (const s of slugs) {
  if (!/^[a-z]+$/.test(s)) die(`LEGAL key ${JSON.stringify(s)} is not a slug app.js's router can match`);
}
if (!slugs.length) die("LEGAL is empty — the shop would answer 404 for every policy page");

const body = JSON.stringify(slugs, null, 2) + "\n";
fs.mkdirSync(path.dirname(OUT), { recursive: true });
const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
if (prev !== body) fs.writeFileSync(OUT, body, "utf8");
console.log(
  "pack-legal: " + slugs.length + " policy slug(s) — " + slugs.join(", ") + (prev === body ? " (unchanged)" : ""),
);
